### PR TITLE
only add @compileTimeOnly if it is not already defined

### PR DESCRIPTION
**Pull request by Philippus**
solves https://github.com/scalamacros/paradise/issues/90

### CODE REVIEW

**Comment by xeno-by** [comment]
LGTM. Thank you!

**Comment by xeno-by** [comment]
@Philippus How would you like to see this published? We could cut a `2.1.1` across supported versions of Scala, or we could silently roll this functionality in the `2.1.0` release starting from Scala 2.12.2.

**Comment by Philippus** [comment]
To me it doesn't sound like a huge problem that warrants a separate release, so I would say put it in the `2.1.0` release. Or does this mean that it will only be fixed for Scala 2.12.2?

**Comment by Philippus** [comment]
it doesn't look like this was published yet? And we are at the `2.1.0` release.

**Comment by xeno-by** [comment]
What version of Scala are you using?

**Comment by Philippus** [comment]
Let's add it to `2.12.2` ?

**Comment by xeno-by** [comment]
Looks like I didn't cherry-pick this commit to the branches supporting recent versions of Scala. Neither 2.11.11, nor 2.12.2 releases of paradise have this logic :(

I suggest we cut a 2.1.1 release. What do you think?

**Comment by Philippus** [comment]
Sounds good to me!

**Comment by xeno-by** [comment]
Published: https://oss.sonatype.org/content/repositories/releases/org/scalamacros/paradise_2.12.2/2.1.1/.

Sorry for the significant delay in responses!

**Pull request merged**
