### PR TITLE
Remove handling of @bridge annotation

### PR DESCRIPTION
**Pull request by NthPortal**

### CODE REVIEW

**Comment by NthPortal** [comment]
I believe this is all that is needed to work with scala/scala#6319, but I could be mistaken.

I'm also not sure if this is the right branch to PR to - I'm happy to change it if not.

**Review by xeno-by — CHANGES_REQUESTED** [review]
Please resubmit the pull request against the newly created 2.13.x branch. Otherwise, this is good to go! Thank you for following up on your PR to scala/scala 👍

**Comment by NthPortal** [comment]
No problem! I've changed the base branch (which is a thing you can do without creating a new PR now!)

**Comment by xeno-by** [comment]
Wow neat!

**Comment by NthPortal** [comment]
I would love to know when they added that feature, because I only learned about it a couple weeks ago when I saw Miles do it on a PR

Edit: it happened in [2016](https://blog.github.com/2016-08-15-change-the-base-branch-of-a-pull-request/), apparently

**Comment by SethTisue** [comment]
thanks @NthPortal and @xeno-by! I'll try the new branch in the 2.13 community build.

**Pull request merged**
